project:
  type: website
  output-dir: docs

website:
  title: "website-playground"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: "Pillar-BS5-v2.0.1/Pillar-BS5-v2.0.1/assets/scss/pillar-1.scss"
    css: styles.css
    toc: true

editor: visual

